name: pragmatic_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Chapter 12-15 (API + parsing)
  http: ^1.2.2

  # Chapter 11 (persist theme)
  shared_preferences: ^2.3.2

  # Chapter 14-15 (open url)
  url_launcher: ^6.3.0

  # optional
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/book_cover.png
    - assets/flutter_icon.png


  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf

dependency_overrides:
  file: ^7.0.0
  platform: ^3.1.0
  path_provider_platform_interface: ^2.1.2
